// frameworks_react_angular_vue/2_vue/3_vuejs-intro-final/src/App.vue
<template>
    <div id="app">
        <div>
            <router-link to="/">Home</router-link>
            <router-link to="/blog">Blog</router-link>
            <router-link to="/account">Account</router-link>
        </div>
        <router-view></router-view>
        <!--<app-user></app-user>-->
        <p>This is a test!</p>
    </div>
</template>

<script>
    export default {
        name: 'app',
        data () {
            return {
                msg: 'Welcome to Your Vue.js App'
            }
        }
    }
</script>

// frameworks_react_angular_vue/3_react/3_react_spq_example/src/App.js
import React, { Component } from 'react';
import { BrowserRouter as Router, Route, Link } from 'react-router-dom';
import './App.css';
import User from './components/User';
import Account from './components/Account';
import Blog from './components/Blog';

class App extends Component {
  render() {
    return (
      <Router>
        <div>
          <div>
            <Link to="/">Home</Link> |
            <Link to="/account">Account</Link> |
            <Link to="/blog">Blog</Link>
          </div>
          <hr/>
          <Route exact path="/" component={User} />
          <Route path="/account" component={Account} />
          <Route path="/blog" component={Blog} />
        </div>
      </ Router>
    );
  }
}

export default App;
